---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0.1
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmanager-app
  template:
    metadata:
      labels:
        app: wordsmanager-app
    spec:
      containers:
        - name: wordsmanager-container
          image: tomasrandom/wordsmanager-app:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombpartyserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombpartyserver-app
  template:
    metadata:
      labels:
        app: bombpartyserver-app
    spec:
      containers:
        - name: bombpartyserver-container
          image: tomasrandom/bombpartyserver-app:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombpartyclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombpartyclient-app
  template:
    metadata:
      labels:
        app: bombpartyclient-app
    spec:
      containers:
        - name: bombpartyclient-container
          image: tomasrandom/bombpartyclient-app:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bombpartyclient-service
spec:
  selector:
    app: bombpartyclient-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
