---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0.1
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsManager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsManager-app
  template:
    metadata:
      labels:
        app: wordsManager-app
    spec:
      containers:
        - name: wordsManager-container
          image: tomasrandom/wordsmanager-app:latest

---
apiVersion: v1
kind: Service
metadata:
  name: wordsManager-service
spec:
  selector:
    app: wordsManager-app
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombPartyServer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombPartyServer-app
  template:
    metadata:
      labels:
        app: bombPartyServer-app
    spec:
      containers:
        - name: bombPartyServer-container
          image: tomasrandom/bombpartyserver-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: bombPartyServer-service
spec:
  selector:
    app: bombPartyServer-app
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombPartyClient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bombPartyClient-app
  template:
    metadata:
      labels:
        app: bombPartyClient-app
    spec:
      containers:
        - name: bombPartyClient-container
          image: tomasrandom/bombpartyclient-app:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bombPartyClient-service
spec:
  selector:
    app: bombPartyClient-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
